### PR TITLE
Fix the build with clang-3.8.0.

### PR DESCRIPTION
**Pull request by orbea**
This fixes the build with `clang-3.8.0` in Slackare-14.2.

See https://github.com/arescentral/antares/issues/308#issuecomment-572625262

Fixes https://github.com/arescentral/antares/issues/308

### CODE REVIEW

**Comment by orbea** [comment]
Thanks for pointing that out, I'm not very experienced with c++ unfortunately. Both `<cstdlib>` and `<cmath>` fix the build issue so I updated this PR with `<cstdlib>` since I am not sure which header you would prefer or that it matters?

The error is:
```
ninja: Entering directory `out/cur'
[59/208] CXX obj/src/drawing/libantares-drawing.styled-text.o
FAILED: obj/src/drawing/libantares-drawing.styled-text.o 
clang++ -MMD -MF obj/src/drawing/libantares-drawing.styled-text.o.d -DNDEBUG -I../../../include -Igen/include -I../../../ext/libsfz/include/all -I../../../ext/libsfz/include/posix -I../../../ext/procyon/src/cpp/include -I../../../ext/procyon/src/c/include -Os -Wall -Werror -Wno-sign-compare -Wno-deprecated-declarations -ftemplate-depth=1024 -std=c++11 -stdlib=libc++ -c ../../../src/drawing/styled-text.cpp -o obj/src/drawing/libantares-drawing.styled-text.o
../../../src/drawing/styled-text.cpp:538:29: error: no member named 'abs' in namespace 'std'; did you mean simply 'abs'?
    int32_t       diff    = std::abs(h - curr->second.bounds.left);
                            ^~~~~~~~
                            abs
/usr/bin/../include/c++/v1/math.h:654:1: note: 'abs' declared here
abs(long double __lcpp_x) _NOEXCEPT {return fabsl(__lcpp_x);}
^
../../../src/drawing/styled-text.cpp:540:25: error: no member named 'abs' in namespace 'std'; did you mean simply 'abs'?
        int32_t diff2 = std::abs(h - curr->second.bounds.left);
                        ^~~~~~~~
                        abs
/usr/bin/../include/c++/v1/math.h:654:1: note: 'abs' declared here
abs(long double __lcpp_x) _NOEXCEPT {return fabsl(__lcpp_x);}
^
../../../src/drawing/styled-text.cpp:566:29: error: no member named 'abs' in namespace 'std'; did you mean simply 'abs'?
    int32_t       diff    = std::abs(h - curr->second.bounds.left);
                            ^~~~~~~~
                            abs
/usr/bin/../include/c++/v1/math.h:654:1: note: 'abs' declared here
abs(long double __lcpp_x) _NOEXCEPT {return fabsl(__lcpp_x);}
^
../../../src/drawing/styled-text.cpp:568:25: error: no member named 'abs' in namespace 'std'; did you mean simply 'abs'?
        int32_t diff2 = std::abs(h - curr->second.bounds.left);
                        ^~~~~~~~
                        abs
/usr/bin/../include/c++/v1/math.h:654:1: note: 'abs' declared here
abs(long double __lcpp_x) _NOEXCEPT {return fabsl(__lcpp_x);}
^
4 errors generated.
[66/208] CXX obj/src/data/libantares-data.action.o
ninja: build stopped: subcommand failed.
Makefile:16: recipe for target 'build' failed
make: *** [build] Error 1
```

**Comment by sfiera** [comment]
I think `<cstdlib>` is probably better? I referred to https://en.cppreference.com/w/cpp/numeric/math/abs and what I think it’s saying is that `std::abs()` moved from `<cstdlib>` to `<cmath>` in C++17. Antares is using C++11.

It looks like I was slightly wrong. The suggestion is:
`abs(long double __lcpp_x) _NOEXCEPT {return fabsl(__lcpp_x);}`
So it’s actually `::abs(double)`, not `::abs(int)`. And, while it would be safe, I think it’s probably best not to do `(int32_t)::abs((double)y)`.

Thanks!
