### ISSUE TITLE
Build failure with clang10

### ISSUE THREAD

**Issue by orbea** [arescentral/antares#310]
OS: `Slackware64-current`
compiler: `clang-10.0.0`
antares: `0.9.0`

antares does not build with `clang-10.0.0`.
```
samu: job failed: clang++ -MMD -MF obj/src/glfw/antares-glfw.video-driver.o.d -DNDEBUG -I../../../include -Igen/include -I../../../ext/libsfz/include/all -I../../../ext/libsfz/include/posix -I../../../ext/procyon/src/cpp/include -I../../../ext/procyon/src/c/include -I../../../ext/libzipxx/include -Os -Wall -Werror -Wno-sign-compare -Wno-deprecated-declarations -ftemplate-depth=1024 -std=c++11 -stdlib=libc++ -c ../../../src/glfw/video-driver.cpp -o obj/src/glfw/antares-glfw.video-driver.o
../../../src/glfw/video-driver.cpp:36:9: error: array designators are a C99 extension [-Werror,-Wc99-designator]
        [GLFW_KEY_SPACE]      = Key::SPACE,
        ^~~~~~~~~~~~~~~~
../../../src/glfw/video-driver.cpp:36:9: error: mixture of designated and non-designated initializers in the same initializer list is a C99 extension [-Werror,-Wc99-designator]
        [GLFW_KEY_SPACE]      = Key::SPACE,
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../../src/glfw/video-driver.cpp:39:9: note: first non-designated initializer is here
        Key::MINUS,
        ^~~~~~~~~~
2 errors generated.
samu: subcommand failed
make: *** [Makefile:16: all] Error 1
```

**Comment by orbea** [comment]
Issue still exists in the master. https://github.com/arescentral/antares/commit/35320fb076b50e15100cb07b9d6b4b9c11fbd563
```
ninja: Entering directory `out/cur'
[9/208] CXX obj/src/glfw/antares-glfw.video-driver.o
FAILED: obj/src/glfw/antares-glfw.video-driver.o 
clang++ -MMD -MF obj/src/glfw/antares-glfw.video-driver.o.d -DNDEBUG -I../../../include -Igen/include -I../../../ext/libsfz/include/all -I../../../ext/libsfz/include/posix -I../../../ext/procyon/src/cpp/include -I../../../ext/procyon/src/c/include -Os -Wall -Werror -Wno-sign-compare -Wno-deprecated-declarations -ftemplate-depth=1024 -std=c++11 -stdlib=libc++ -c ../../../src/glfw/video-driver.cpp -o obj/src/glfw/antares-glfw.video-driver.o
../../../src/glfw/video-driver.cpp:36:9: error: array designators are a C99 extension [-Werror,-Wc99-designator]
        [GLFW_KEY_SPACE]      = Key::SPACE,
        ^~~~~~~~~~~~~~~~
../../../src/glfw/video-driver.cpp:36:9: error: mixture of designated and non-designated initializers in the same initializer list is a C99 extension [-Werror,-Wc99-designator]
        [GLFW_KEY_SPACE]      = Key::SPACE,
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../../src/glfw/video-driver.cpp:39:9: note: first non-designated initializer is here
        Key::MINUS,
        ^~~~~~~~~~
2 errors generated.
[16/208] CXX obj/src/data/libantares-data.level.o
ninja: build stopped: subcommand failed.
make: *** [Makefile:16: build] Error 1
```

**Comment by sfiera** [comment]
Oops, yeah. C allows that since C99 but C++ doesn’t until C++20. I guess Clang got stricter.

**Comment by orbea** [comment]
Fixed in https://github.com/arescentral/antares/pull/311.
